# Data Columns in Each Dataset

Calibrated_Data_Columns = {
    "B1dw"         : "Spectrometer data Bands 1 downwelling",
    "B1uw"         : "Spectrometer data Bands 1 upwelling",
    "B2dw"         : "Spectrometer data Bands 1 downwelling",
    "B2uw"         : "Spectrometer data Bands 1 upwelling",
    "B3dw"         : "Spectrometer data Bands 1 downwelling",
    "B3uw"         : "Spectrometer data Bands 1 upwelling",
    "B4dw"         : "Spectrometer data Bands 1 downwelling",
    "B4uw"         : "Spectrometer data Bands 1 upwelling",
    "B5dw"         : "Spectrometer data Bands 1 downwelling",
    "B5uw"         : "Spectrometer data Bands 1 upwelling",
    "B6dw"         : "Spectrometer data Bands 1 downwelling",
    "B6uw"         : "Spectrometer data Bands 1 upwelling",
    "B7dw"         : "Spectrometer data Bands 1 downwelling",
    "B7uw"         : "Spectrometer data Bands 1 upwelling",
    "LWdw"         : "Long wave downwelling, hourly mean",
    "LWuw"         : "Long wave upwelling, hourly mean",
    "P"            : "Pressure",
    "PARdw"        : "Photosynthetically Active Radiation downwelling",
    "PARuw"        : "Photosynthetically Active Radiation upwelling",
    "RH"           : "Relative humidity",
    "SWdw"         : "Short wave downwelling, hourly mean",
    "SWuw"         : "Short wave upwelling, hourly mean",
    "Tabove"       : "Sky temperature",
    "Tair"         : "Air temperature",
    "Tbelow"       : "Leaf/Ground temperature",
    "tair_version" : "UNKNOWN"
}

Hourly_Data_Columns = {
    "B1dw"         : "Spectrometer data Bands 1 downwelling",
    "B1uw"         : "Spectrometer data Bands 1 upwelling",
    "B2dw"         : "Spectrometer data Bands 1 downwelling",
    "B2uw"         : "Spectrometer data Bands 1 upwelling",
    "B3dw"         : "Spectrometer data Bands 1 downwelling",
    "B3uw"         : "Spectrometer data Bands 1 upwelling",
    "B4dw"         : "Spectrometer data Bands 1 downwelling",
    "B4uw"         : "Spectrometer data Bands 1 upwelling",
    "B5dw"         : "Spectrometer data Bands 1 downwelling",
    "B5uw"         : "Spectrometer data Bands 1 upwelling",
    "B6dw"         : "Spectrometer data Bands 1 downwelling",
    "B6uw"         : "Spectrometer data Bands 1 upwelling",
    "B7dw"         : "Spectrometer data Bands 1 downwelling",
    "B7uw"         : "Spectrometer data Bands 1 upwelling",
    "LWdw"         : "Long wave downwelling, hourly mean",
    "LWuw"         : "Long wave upwelling, hourly mean",
    "LfW"          : "Leaf wetness",
    "P"            : "Pressure",
    "SLP"          : "Sea Level Pressure",
    "PARdw"        : "Photosynthetically Active Radiation downwelling",
    "PARuw"        : "Photosynthetically Active Radiation upwelling",
    "RH"           : "Relative humidity",
    "SWdw"         : "Short wave downwelling, hourly mean",
    "SWuw"         : "Short wave upwelling, hourly mean",
    "Tabove"       : "Sky temperature",
    "Tair"         : "Air temperature",
    "Tbelow"       : "Leaf/Ground temperature",
    "Tdew"         : "Dew temperature",
    "prate"        : "Precipitation rate",
    "precip"       : "Precipitation total"
}

Daily_Data_Columns = {
    "CGDD"              : "Cumulative Growing Degree Days, accumulated from time of install",
    "Cl"                : "Chlorophyll Index",
    "ET"                : "Evapotranspiration (ET_o)",
    "GDD"               : "Growing Degree Days for the day",
    "LfAirDelta"        : "Leaf to Air temperature difference",
    "NDVI"              : "Normalized Difference Vegetation Index",
    "SWdw"              : "Short wave downwelling, hourly mean",
    "maxT"              : "Daily Maximum Temperature",
    "meanT"             : "Daily Mean Temperature",
    "minT"              : "Daily Minimum Temperature",
    "prate"             : "Precipitation rate",
    "precip"            : "Precipitation total",
    "SLP"               : "Sea Level Pressure",
    "Kc"                : "Crop coefficient (K_c)",
    "ETc"               : "Crop Evapotranspiration",
    "mean_tbelow"       : "Daily Mean Leaf/Ground temperature",
    "lfw"               : "Leaf wetness",
    "crop_water_demand" : "Crop Water Demand",
    "sunshine_duration" : "Sunshine Duration"
}

# Units for Data Columns in Each Dataset

Calibrated_Data_Columns_Units = {
    "B1dw"         : "W/m^2/band",
    "B1uw"         : "W/m^2/band",
    "B2dw"         : "W/m^2/band",
    "B2uw"         : "W/m^2/band",
    "B3dw"         : "W/m^2/band",
    "B3uw"         : "W/m^2/band",
    "B4dw"         : "W/m^2/band",
    "B4uw"         : "W/m^2/band",
    "B5dw"         : "W/m^2/band",
    "B5uw"         : "W/m^2/band",
    "B6dw"         : "W/m^2/band",
    "B6uw"         : "W/m^2/band",
    "B7dw"         : "W/m^2/band",
    "B7uw"         : "W/m^2/band",
    "LWdw"         : "W/m^2",
    "LWuw"         : "W/m^2",
    "P"            : "kPA",
    "PARdw"        : "uE/m^2/s",
    "PARuw"        : "uE/m^2/s",
    "RH"           : "between 0 and 1",
    "SWdw"         : "W/m^2",
    "SWuw"         : "W/m^2",
    "Tabove"       : "C",
    "Tair"         : "C",
    "Tbelow"       : "C",
    "tair_version" : "UNKNOWN"
}

Hourly_Data_Columns_Units = {
    "B1dw"         : "W/m^2/band",
    "B1uw"         : "W/m^2/band",
    "B2dw"         : "W/m^2/band",
    "B2uw"         : "W/m^2/band",
    "B3dw"         : "W/m^2/band",
    "B3uw"         : "W/m^2/band",
    "B4dw"         : "W/m^2/band",
    "B4uw"         : "W/m^2/band",
    "B5dw"         : "W/m^2/band",
    "B5uw"         : "W/m^2/band",
    "B6dw"         : "W/m^2/band",
    "B6uw"         : "W/m^2/band",
    "B7dw"         : "W/m^2/band",
    "B7uw"         : "W/m^2/band",
    "LWdw"         : "W/m^2",
    "LWuw"         : "W/m^2",
    "LfW"          : "[-, 1]",
    "P"            : "kPA",
    "SLP"          : "kPA",
    "PARdw"        : "uE/m^2/s",
    "PARuw"        : "uE/m^2/s",
    "RH"           : "between 0 and 1",
    "SWdw"         : "W/m^2",
    "SWuw"         : "W/m^2",
    "Tabove"       : "C",
    "Tair"         : "C",
    "Tbelow"       : "C",
    "Tdew"         : "C",
    "prate"        : "mm/hr",
    "precip"       : "mm"
}

Daily_Data_Columns_Units = {
    "CGDD"              : "C-days",
    "Cl"                : "Unitless index",
    "ET"                : "mm",
    "GDD"               : "C-days",
    "LfAirDelta"        : "C",
    "NDVI"              : "Unitless index between -1 and 1",
    "SWdw"              : "Megajoules/m^2",
    "maxT"              : "C",
    "meanT"             : "C",
    "minT"              : "C",
    "prate"             : "mm/day",
    "precip"            : "mm",
    "SLP"               : "kPa",
    "Kc"                : "Unitless",
    "ETc"               : "mm",
    "mean_tbelow"       : "C",
    "lfw"               : "[-, 1]",
    "crop_water_demand" : "UNKNOWN",
    "sunshine_duration" : "UNKNOWN"
}

import arable
from   arable.client   import ArableClient as a
a = a()
def arable_query(a, b, c, d, e, f, g):
    df = a.query(select = str(a),
               format = str(b),
               devices = c,
               measure = str(d),
               order = str(e),
               end = f,
               start = g,
               limit = 100000000)
    return df